{{- if not (eq $.Values.mode "agent") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubeconfig-secret-name" .Release }}
type: Opaque
data:
  {{/* Secret limits are 1MB. The largest single kubeconfig we've seen is about
  10kb, so there's about a 100 kubeconfig limit here give or take some bytes.

  If we hit a use case where users are running into size limits on secrets we
  can revisit the decision to pack them into a single secret.
  */}}
  {{ range .Values.accounts }}
  {{ $.Release.Name | lower }}-{{ .name }}: {{ .kubeconfig | b64enc }}
  {{- end }}
{{- end }}
